Remove sles/SUSE from robotest configs
We no longer have any customers that use SLES, and this test is
currently broken because GCP removed the SLES disk image robotest
depends on, resulting in the following error:

   Error: Error resolving image name 'suse-cloud/sles-15-sp2-v20201014': Could not find image or family suse-cloud/sles-15-sp2-v20201014

(cherry picked from commit a7137a4c89625dc31faf41300f90d6a361f97235)