Fix the unexpected signal error during build on darwin:
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff6811d70a]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff6811d70a
...

Introduced in this commit: 6ff175a06b53f63d639842c196aa2763ee4a69dc (https://github.com/gravitational/gravity/pull/2594)